name: Sync to HF and ModelScope

on:
  push:
    paths:
      - 'sft_model_eval/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone and update HuggingFace repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone "https://oauth2:$HF_TOKEN@huggingface.co/datasets/yj12869741/SeedBench" hf_repo
          
          rm -rf hf_repo/one-shot
          rm -rf hf_repo/zero-shot
          cp -r sft_model_eval/one-shot hf_repo/
          cp -r sft_model_eval/zero-shot hf_repo/
          
          cd hf_repo
          git add .
          git commit -m "Update sft_model_eval from GitHub"
          git push origin main

      - name: Clone and update ModelScope repo
        env:
          MODELSCOPE_TOKEN: ${{ secrets.MODELSCOPE_TOKEN }}
        run: |
          git clone "https://oauth2:$MODELSCOPE_TOKEN@www.modelscope.cn/y12869741/SeedBench.git" ms_repo
          
          rm -rf ms_repo/one-shot
          rm -rf ms_repo/zero-shot
          cp -r sft_model_eval/one-shot ms_repo/
          cp -r sft_model_eval/zero-shot ms_repo/
          
          cd ms_repo
          git add .
          git commit -m "Update sft_model_eval from GitHub"
          git push origin master